package net.minecraftforge.fml.common.eventhandler;

import net.minecraft.launchwrapper.LaunchClassLoader;
import net.minecraftforge.fml.common.eventhandler.impl.ExampleEvent;
import net.minecraftforge.fml.common.eventhandler.impl.legacy.LegacyEventBus;
import net.minecraftforge.fml.common.eventhandler.impl.legacy.TestClassLoader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Type;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.Blackhole;

import java.net.URL;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Function;

import static org.objectweb.asm.Opcodes.*;

/**
 * @author ZZZank
 */
@BenchmarkMode(Mode.AverageTime)
@State(Scope.Thread)
@Fork(1)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@Warmup(iterations = 3)
@Measurement(iterations = 5)
public class BusPerformanceTest {
    public static final String PACKAGE = BusPerformanceTest.class.getPackage().getName();
    public static final String METHOD_DESC = Type.getMethodDescriptor(
        Type.getType(void.class),
        Type.getType(ExampleEvent.class)
    );
    private static final Type TYPE_EVENT = Type.getType(ExampleEvent.class);
    public static final LaunchClassLoader CLASS_LOADER = new TestClassLoader(BusPerformanceTest.class.getClassLoader());
    public static final AtomicInteger ID = new AtomicInteger();

//    @Benchmark
    public void register10000Modern(Blackhole bh) {
        doTest(bh, l -> new EventBus(), 10000, 0);
    }

//    @Benchmark
    public void register10000Legacy(Blackhole bh) {
        doTest(bh, LegacyEventBus::new, 10000, 0);
    }

    @Benchmark
//    @Test
    public void register1000test10000Modern() {
        doTest(null, l -> new EventBus(), 1000, 10000);
    }

    @Benchmark
    public void register1000test10000Legacy(Blackhole bh) {
        doTest(bh, LegacyEventBus::new, 1000, 10000);
    }

    public void doTest(Blackhole bh, Function<LaunchClassLoader, EventBus> bus, int registerAmount, int postAmount) {
        var loader = new TestClassLoader(new URL[0]);
        Thread.currentThread().setContextClassLoader(loader);
        var eventBus = bus.apply(loader);

        var bytes = generateClass(loader, registerAmount);
        Class<?> clazz = null;
        try {
            clazz = eventBus instanceof LegacyEventBus
                ? loader.defineClass(bytes.getKey(), bytes.getValue())
                : EventListenerFactory.LOOKUP.defineClass(bytes.getValue());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        eventBus.register(clazz);

        for (int i = 0; i < postAmount; i++) {
            var event = new ExampleEvent();
            eventBus.post(event);
//            bh.consume(event);
        }
    }

    private static Map.Entry<String, byte[]> generateClass(LaunchClassLoader loader, int handlerCount) {
        var cw = new ClassWriter(0);
        MethodVisitor mv;

        var className = PACKAGE + '.' + "GeneratedListeners" + ID.getAndIncrement();
        cw.visit(
            V21,
            ACC_PUBLIC | ACC_SUPER,
            className.replace('.', '/'),
            null,
            Type.getInternalName(Object.class),
            new String[0]
        );
        cw.visitSource("Example.java", null);


        {
            mv = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
            mv.visitCode();
            Label label0 = new Label();
            mv.visitLabel(label0);
            mv.visitLineNumber(8, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
            mv.visitInsn(RETURN);
            Label label1 = new Label();
            mv.visitLabel(label1);
            mv.visitLocalVariable(
                "this",
                "Lnet/minecraftforge/fml/common/eventhandler/Example;",
                null,
                label0,
                label1,
                0
            );
            mv.visitMaxs(1, 1);
            mv.visitEnd();
        }

        for (int i = 0; i < handlerCount; i++) {
            // codes below modified from codes generated by ASM Bytecode Outline
            mv = cw.visitMethod(
                ACC_PUBLIC | ACC_STATIC,
                "acceptEvent" + i,
                "(Lnet/minecraftforge/fml/common/eventhandler/impl/ExampleEvent;)V",
                null,
                null
            );
            {
                var av = mv.visitAnnotation(
                    "Lnet/minecraftforge/fml/common/eventhandler/SubscribeEvent;",
                    true
                );
                av.visitEnd();
            }
            mv.visitCode();
            Label label0 = new Label();
            mv.visitLabel(label0);
            mv.visitLineNumber(12, label0);
            mv.visitVarInsn(ALOAD, 0);
            mv.visitMethodInsn(
                INVOKEVIRTUAL,
                "net/minecraftforge/fml/common/eventhandler/impl/ExampleEvent",
                "increment",
                "()V",
                false
            );
            Label label1 = new Label();
            mv.visitLabel(label1);
            mv.visitLineNumber(13, label1);
            mv.visitInsn(RETURN);
            Label label2 = new Label();
            mv.visitLabel(label2);
            mv.visitLocalVariable(
                "event",
                "Lnet/minecraftforge/fml/common/eventhandler/impl/ExampleEvent;",
                null,
                label0,
                label2,
                0
            );
            mv.visitMaxs(1, 1);
            mv.visitEnd();
        }

        cw.visitEnd();
        return Map.entry(className, cw.toByteArray());
    }
}
